version: "3"
services: 
    loadBalancer:
        image: haproxy
        ports: 
          - "8080:8080"
        volumes: 
          - ./haproxy:/usr/local/etc/haproxy
    voucher1:
      image: ahmed1992/vouchers:v1
      ports: 
        - "5000:5000"
      restart: always
      environment: 
        - "PORT=5000"
        - "dbUrl=mongodb+srv://HmJpNSRhHWMEaz65:HmJpNSRhHWMEaz65@cluster0.ur6so.mongodb.net/myFirstDatabase?retryWrites=true&w=majority"
    voucher2:
      image: ahmed1992/vouchers:v1
      ports:
        - "5001:5001"
      restart: always
      environment: 
        - "PORT=5001"
        - "dbUrl=mongodb+srv://HmJpNSRhHWMEaz65:HmJpNSRhHWMEaz65@cluster0.ur6so.mongodb.net/myFirstDatabase?retryWrites=true&w=majority"